[workspace]
resolver = "2"
members = ["crates/*", "xtask", "examples"]
exclude = ["fuzz"]

[workspace.package]
edition = "2021"
rust-version = "1.84"
license = "MIT OR Apache-2.0"
authors = ["TPT Solutions"]
homepage = "https://github.com/tpt-solutions/tpt-crypto"
repository = "https://github.com/tpt-solutions/tpt-crypto"
version = "0.1.0"
description = "High-assurance, constant-time cryptographic substrate (pure Rust, no_std-first)."

[workspace.dependencies]
tpt-crypto-core = { version = "0.1.0", path = "crates/tpt-crypto-core", default-features = false }
tpt-crypto-ct = { version = "0.1.0", path = "crates/tpt-crypto-ct", default-features = false }
tpt-crypto-kem = { version = "0.1.0", path = "crates/tpt-crypto-kem", default-features = false }
tpt-crypto-field = { version = "0.1.0", path = "crates/tpt-crypto-field", default-features = false }
tpt-crypto-curve = { version = "0.1.0", path = "crates/tpt-crypto-curve", default-features = false }
tpt-crypto-hash = { version = "0.1.0", path = "crates/tpt-crypto-hash", default-features = false }
tpt-crypto-aead = { version = "0.1.0", path = "crates/tpt-crypto-aead", default-features = false }
tpt-crypto-sig = { version = "0.1.0", path = "crates/tpt-crypto-sig", default-features = false }
tpt-crypto-mpc = { version = "0.1.0", path = "crates/tpt-crypto-mpc", default-features = false }
tpt-crypto-zk = { version = "0.1.0", path = "crates/tpt-crypto-zk", default-features = false }
tpt-crypto = { version = "0.1.0", path = "crates/tpt-crypto", default-features = false }
digest = { version = "0.10", default-features = false }
proptest = "1"

[workspace.lints.rust]
unsafe_code = "forbid"
unsafe_op_in_unsafe_fn = "deny"
missing_docs = "warn"

[workspace.lints.clippy]
all = "warn"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"
overflow-checks = true
