//! `tpt-crypto-mpc` — secure multi-party computation primitives.
//!
//! Pure Rust, `#![no_std]` (plus `alloc`), constant-time-by-construction. The
//! crate provides the building blocks for two-party / multi-party computation:
//!
//! * **Additive secret sharing** over any prime field ([`Share`], [`share_secret`],
//!   [`reconstruct`]). Operations on shares ([`Share::add`], [`Share::scale`]) are
//!   local and constant-time.
//! * **Beaver triples** ([`BeaverTriple`]) for precomputed, constant-time
//!   multiplication of secret-shared values — generated by a trusted dealer
//!   ([`BeaverTriple::deal`]), by base oblivious transfer ([`BeaverTriple::deal_from_base_ot`]),
//!   or batched via IKNP OT extension ([`BeaverTriple::deal_many_from_iknp`]).
//! * **Oblivious transfer**: Chou–Orlandi 1-of-2 base OT over Curve25519
//!   ([`ot`]), 1-of-N built from 1-of-2 ([`ot::transfer_1ofn`]), and the IKNP
//!   OT extension ([`iknp`]) that turns a few base OTs into many.
//!
//! All protocols are written for an *idealized in-process channel*: the sender
//! and receiver halves run in the same process and exchange their wire messages
//! through the typed step functions. This keeps the implementation auditable and
//! fully exercised by the property tests; wiring the messages over a real network
//! is a mechanical drop-in.
//!
//! # Constant-time contract
//!
//! Arithmetic, share operations, and the OT key schedule never branch or index on
//! secret data. Randomness is supplied by [`CryptoRng`]; rejection sampling during
//! field-element generation may loop a variable number of times, which leaks only
//! the (public) fact that a sample was reduced — never the value.

#![no_std]
#![forbid(unsafe_code)]
#![warn(missing_docs)]

extern crate alloc;

#[cfg(feature = "std")]
extern crate std;

pub use tpt_crypto_core::CryptoRng;
pub use tpt_crypto_core::Error;
pub use tpt_crypto_core::Result;

pub mod beaver;
pub mod iknp;
pub mod ot;

pub use beaver::{BeaverTriple, multiply};
pub use field_share::{reconstruct, share_secret, share_secret_2, FieldCodec, SampleField, Share};
pub use iknp::extend_1of2;
pub use ot::{transfer_1ofn, transfer_base_ot_1of2};

mod field_share;
